### ISSUE TITLE
proj4 in PROJ v 6.0.0 and above

### ISSUE THREAD

**Issue by mdsumner** [s-u/proj4#3]
Hi there, Roger Bivand has told me that proj4 cannot work with PROJ 6: 

>  proj4 will not install where proj_api.h is absent. This can be fixed (add "-
> DACCEPT_USE_OF_DEPRECATED_PROJ_API_H" to PKG_CPPFLAGS) for PROJ 6, but 
> PROJ 7 due in 10 months will remove this option.

I'm mostly out of my depth configuring installs at this level, but I will create a PR if I can get it working. 

Thank you.

**Comment by mdsumner** [comment]
This seems to work, I modified line 22 in configure.ac: 

```
CPPFLAGS="${CPPFLAGS} ${PKG_CPPFLAGS} -DACCEPT_USE_OF_DEPRECATED_PROJ_API_H"
```

and also ran

```R
tools::package_native_routine_registration_skeleton("../proj4", "src/init.c",character_only = FALSE)
```

R CMD check reports: 

```

❯ checking compilation flags in Makevars ... NOTE
  Package has both ‘src/Makevars.in’ and ‘src/Makevars’.
  Installation with --no-configure' is unlikely to work.  If you intended
  ‘src/Makevars’ to be used on Windows, rename it to ‘src/Makevars.win’
  otherwise remove it.  If ‘configure’ created ‘src/Makevars’, you need a
  ‘cleanup’ script.
```

Any prospects for a CRAN release?

**Comment by s-u** [comment]
Um, any reason why you don't simply set `PKG_CPPFLAGS`? That's the documented way - you don't need to change the package...

**Comment by mdsumner** [comment]
Understood, thanks.

Are you going to release an update to proj4?  There are several fixes since the 2012 version that is on CRAN.

**Comment by haselwarter** [comment]
The package doesn't currently build unless `PKG_CPPFLAGS` is set manually. The fix of defining the CPP macro would certainly save a lot of users some pain, at no harm.

Eventually with the old API being deprecated, this R package will either become obsolete or require an update to the new API. Maybe the crowd over at https://github.com/hrbrmstr/ggalt would be interested in helping maintain the package, seeing how they depend on it.

**Comment by s-u** [comment]
@haselwarter that is a very strong overstatement. No major distributions ship with 6.x -- LTS distros use 4.9.x [except for RH which uses 4.8.x] and most recent non-LTS ones use 5.2.x -- so there is no real impact on users. Only those that choose to live on the edge and get 6.x themselves are impacted and they better know what that are doing.

I didn't close the issue - I'll look into the API change once there is any actual demand.

**Comment by thiagoveloso** [comment]
I am sorry to report that I am also having issues trying to install `proj4` with PROJ6:
```
> install.packages('proj4', type='source', configure.args=c('--enable-proj6'))
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/proj4_1.0-8.1.tar.gz'
Content type 'application/x-gzip' length 40955 bytes (39 KB)
==================================================
downloaded 39 KB

* installing *source* package ‘proj4’ ...
** package ‘proj4’ successfully unpacked and MD5 sums checked
** using staged installation
configure: WARNING: unrecognized options: --enable-proj6
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking proj_api.h usability... no
checking proj_api.h presence... no
checking for proj_api.h... no
checking for pj_init_plus in -lproj... no
configure: error: libproj and/or proj_api.h not found in standard search locations.

*** Install PROJ.4 and if necessary set PKG_CPPFLAGS/PKG_LIBS accordingly.
ERROR: configuration failed for package ‘proj4’
* removing ‘/usr/local/lib/R/site-library/proj4’
* restoring previous ‘/usr/local/lib/R/site-library/proj4’

The downloaded source packages are in
	‘/tmp/RtmpAY4XSI/downloaded_packages’
Warning message:
In install.packages("proj4", type = "source", configure.args = c("--enable-proj6")) :
  installation of package ‘proj4’ had non-zero exit status
```
However, my PROJ6 build is present and working:

```
root@biosphere:/home/thiago/Downloads# proj
Rel. 6.2.0, September 1st, 2019
usage: proj [-bdeEfiIlmorsStTvVwW [args]] [+opt[=arg] ...] [file ...]
```

```
root@biosphere:/home/thiago/Downloads# ls /opt/software/include/proj_*
/opt/software/include/proj_api.h        /opt/software/include/proj_experimental.h             /opt/software/include/proj_symbol_rename.h
/opt/software/include/proj_constants.h  /opt/software/include/proj_json_streaming_writer.hpp
```

```
root@biosphere:/home/thiago/Downloads# echo $PKG_CONFIG_PATH
:/opt/software/lib/pkgconfig
```

```
root@biosphere:/home/thiago/Downloads# pkg-config proj --libs
-L/opt/software/lib -lproj
```

@s-u any hints on how to overcome this?

**Comment by jeroen** [comment]
Looks like both Debian and Fedora have upgraded to proj 6.2.0 in their latest branches.

**Comment by thiagoveloso** [comment]
> I am sorry to report that I am also having issues trying to install `proj4` with PROJ6:
> 
> ```
> > install.packages('proj4', type='source', configure.args=c('--enable-proj6'))
> Installing package into ‘/usr/local/lib/R/site-library’
> (as ‘lib’ is unspecified)
> trying URL 'https://cran.rstudio.com/src/contrib/proj4_1.0-8.1.tar.gz'
> Content type 'application/x-gzip' length 40955 bytes (39 KB)
> ==================================================
> downloaded 39 KB
> 
> * installing *source* package ‘proj4’ ...
> ** package ‘proj4’ successfully unpacked and MD5 sums checked
> ** using staged installation
> configure: WARNING: unrecognized options: --enable-proj6
> checking for gcc... gcc -std=gnu99
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables...
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc -std=gnu99 accepts -g... yes
> checking for gcc -std=gnu99 option to accept ISO C89... none needed
> checking how to run the C preprocessor... gcc -std=gnu99 -E
> checking for grep that handles long lines and -e... /bin/grep
> checking for egrep... /bin/grep -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking proj_api.h usability... no
> checking proj_api.h presence... no
> checking for proj_api.h... no
> checking for pj_init_plus in -lproj... no
> configure: error: libproj and/or proj_api.h not found in standard search locations.
> 
> *** Install PROJ.4 and if necessary set PKG_CPPFLAGS/PKG_LIBS accordingly.
> ERROR: configuration failed for package ‘proj4’
> * removing ‘/usr/local/lib/R/site-library/proj4’
> * restoring previous ‘/usr/local/lib/R/site-library/proj4’
> 
> The downloaded source packages are in
> 	‘/tmp/RtmpAY4XSI/downloaded_packages’
> Warning message:
> In install.packages("proj4", type = "source", configure.args = c("--enable-proj6")) :
>   installation of package ‘proj4’ had non-zero exit status
> ```
> 
> However, my PROJ6 build is present and working:
> 
> ```
> root@biosphere:/home/thiago/Downloads# proj
> Rel. 6.2.0, September 1st, 2019
> usage: proj [-bdeEfiIlmorsStTvVwW [args]] [+opt[=arg] ...] [file ...]
> ```
> 
> ```
> root@biosphere:/home/thiago/Downloads# ls /opt/software/include/proj_*
> /opt/software/include/proj_api.h        /opt/software/include/proj_experimental.h             /opt/software/include/proj_symbol_rename.h
> /opt/software/include/proj_constants.h  /opt/software/include/proj_json_streaming_writer.hpp
> ```
> 
> ```
> root@biosphere:/home/thiago/Downloads# echo $PKG_CONFIG_PATH
> :/opt/software/lib/pkgconfig
> ```
> 
> ```
> root@biosphere:/home/thiago/Downloads# pkg-config proj --libs
> -L/opt/software/lib -lproj
> ```
> 
> @s-u any hints on how to overcome this?

Problem solved by manually setting `PKG_CPPFLAGS` and `PKG_LIBS`:
```
thiago@biosphere:~/proj4$ sudo su
root@biosphere:/home/thiago/proj4# export PKG_CPPFLAGS=-I/opt/software/include
root@biosphere:/home/thiago/proj4# export PKG_LIBS=-L/opt/software/lib
root@biosphere:/home/thiago/proj4# R
> update.packages()
proj4 :
 Version 1.0-8 installed in /usr/local/lib/R/site-library
 Version 1.0-8.1 available at https://cran.rstudio.com
Update? (Yes/no/cancel)
trying URL 'https://cran.rstudio.com/src/contrib/proj4_1.0-8.1.tar.gz'
Content type 'application/x-gzip' length 40955 bytes (39 KB)
==================================================
downloaded 39 KB

* installing *source* package ‘proj4’ ...
** package ‘proj4’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking proj_api.h usability... yes
checking proj_api.h presence... yes
checking for proj_api.h... yes
checking for pj_init_plus in -lproj... yes
configure: creating ./config.status
config.status: creating src/Makevars
** libs
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I/opt/software/include -DACCEPT_USE_OF_DEPRECATED_PROJ_API_H    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c p4.c -o p4.o
gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o proj4.so p4.o -lproj -L/opt/software/lib -L/usr/lib/R/lib -lR
installing to /usr/local/lib/R/site-library/00LOCK-proj4/00new/proj4/libs
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (proj4)

The downloaded source packages are in
	‘/tmp/Rtmp0vBbnr/downloaded_packages’
```
