### ISSUE TITLE
typo in configure.ac "xno"

### ISSUE THREAD

**Issue by mdsumner** [s-u/proj4#5]
This test for "no" prevents configuring for PROJ6: 

https://github.com/s-u/proj4/blob/master/configure.ac#L49

**Comment by s-u** [comment]
Can you elaborate? I don't see any typo there (`x` concatenated with `no` is `xno` which is what we check for). Please reopen with details if you think otherwise or mean something else.

**Comment by mdsumner** [comment]
Just confusion on my part, nvm and sorry.
