### ISSUE TITLE
missing library headers

### ISSUE THREAD

**Issue by adokter** [s-u/proj4#6]
After compiling the proj4 package it currently provides the proj.4 library file (e.g. `proj4.so`) under package directory `proj4/libs`, however not the associated header files (expected under `proj4/include`. These header files are needed as well to compile new source code against the library. 

Could the library headers be added in a next release, or is there a different way of accessing them from the proj4 R package?

**Comment by s-u** [comment]
Adriaan, `proj4.so` is NOT the PROJ library, it is the compiled package and only contains the code from this repo, not the library. If you need PROJ, have a look at `configure.ac` and `src/Makevars.*` in this repo.
